### ISSUE TITLE
   error: unknown package in top-level dependencies: jalik:ufs-cloudinary

### ISSUE THREAD

**Issue by fliip92** [jalik/ufs-example#2]
i clone the example and run it and While selecting package versions i get this error:
   error: unknown package in top-level dependencies: jalik:ufs-cloudinary

**Comment by jalik** [comment]
Hi @fliip92 I am sorry, I was working on a new store using Cloudinary and I commited that by error.
**It's fixed so please update your code** or do it manually :
`meteor remove jalik:ufs-cloudinary`
